name: Go CI

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: go vet
        run: go vet -x ./...
      - name: Check Formatting
        run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - name: Run Tests with Coverage
        run: go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  todoapp-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./examples/todoapp/go.mod      

      - name: Install Docker Model Plugin
        run: |
          # Add Docker's official GPG key
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the repository to Apt sources
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          
          # Install Docker Model Plugin
          sudo apt-get update
          sudo apt-get install -y docker-model-plugin

      - name: Pull Docker Images And Models 
        run: |
          docker model pull gpt-oss:20B-UD-Q4_K_XL &
          docker model pull embeddinggemma:300M-Q8_0 &
          docker compose -f ./examples/todoapp/docker-compose.deps.yml pull &
          wait

      - name: Run TodoApp E2E Tests
        run: |
          cd examples/todoapp
          go test -tags=integration -v ./tests/integration/...